import type { Profile, Project, Task } from "./types";

export const mockProfiles: Profile[] = [
  { id: "u1", full_name: "Adam Novák", avatar_url: null, email: "adam@team.sk" },
  { id: "u2", full_name: "Eva Horváthová", avatar_url: null, email: "eva@team.sk" },
  { id: "u3", full_name: "Marek Kováč", avatar_url: null, email: "marek@team.sk" },
  { id: "u4", full_name: "Lucia Tóthová", avatar_url: null, email: "lucia@team.sk" },
];

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "Redesign webu",
    description: "Nová verzia firemnej stránky",
    color: "#3b82f6",
    owner_id: "u1",
    created_at: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Mobilná aplikácia",
    description: "iOS + Android MVP",
    color: "#0ea5e9",
    owner_id: "u2",
    created_at: new Date().toISOString(),
  },
  {
    id: "p3",
    name: "Marketing Q2",
    description: "Kampane a obsah",
    color: "#ef4444",
    owner_id: "u1",
    created_at: new Date().toISOString(),
  },
];

const today = new Date();
const addDays = (d: number) => new Date(today.getTime() + d * 86400000).toISOString();

export const mockTasks: Task[] = [
  {
    id: "t1",
    project_id: "p1",
    title: "Pripraviť wireframes hlavnej stránky",
    description: "Mobile-first prístup, 3 varianty hero sekcie.",
    priority: "high",
    status: "in_progress",
    assignee_id: "u1",
    created_by: "u1",
    due_date: addDays(1),
    created_at: addDays(-2),
    updated_at: addDays(0),
  },
  {
    id: "t2",
    project_id: "p1",
    title: "Schváliť farebnú paletu",
    description: null,
    priority: "medium",
    status: "todo",
    assignee_id: "u2",
    created_by: "u1",
    due_date: addDays(3),
    created_at: addDays(-1),
    updated_at: addDays(0),
  },
  {
    id: "t3",
    project_id: "p2",
    title: "Setup CI pipeline",
    description: "GitHub Actions + TestFlight deploy.",
    priority: "high",
    status: "todo",
    assignee_id: "u3",
    created_by: "u2",
    due_date: addDays(0),
    created_at: addDays(-3),
    updated_at: addDays(0),
  },
  {
    id: "t4",
    project_id: "p2",
    title: "Návrh onboarding obrazoviek",
    description: null,
    priority: "low",
    status: "todo",
    assignee_id: "u4",
    created_by: "u2",
    due_date: addDays(7),
    created_at: addDays(-1),
    updated_at: addDays(0),
  },
  {
    id: "t5",
    project_id: "p3",
    title: "Plán content kalendára",
    description: "12 týždňov dopredu.",
    priority: "medium",
    status: "in_progress",
    assignee_id: "u1",
    created_by: "u1",
    due_date: addDays(2),
    created_at: addDays(-4),
    updated_at: addDays(0),
  },
  {
    id: "t6",
    project_id: "p3",
    title: "Newsletter šablóna",
    description: null,
    priority: "low",
    status: "done",
    assignee_id: "u4",
    created_by: "u1",
    due_date: addDays(-1),
    created_at: addDays(-6),
    updated_at: addDays(-1),
  },
];
